version: "3.7"

networks:
  init:
volumes:
  owncast-data:

services:
  owncast:
    image: gabekangas/owncast:latest
    ports:
      - 4343:8080
      - 1935:1935
    networks:
      - init
    volumes:
      - owncast-data:/app/data