name: Label handling

on:
  pull-request:
    branches:
      - main
      - staging

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Require Labels
        # You may pin to the exact commit or the version.
        # uses: mheap/github-action-required-labels@c1021ae643be7256d21caec582af08f09f71379e
        uses: mheap/github-action-required-labels@v1
        with:
          # Comma separated list of labels to match
          labels: "Verified"
          # The mode of comparison to use. One of: exactly, minimum, maximum
          mode: exactly
          # The required number of labels to match
          count: 1

      - name: Merge PR
        # You may pin to the exact commit or the version.
        # uses: ridedott/merge-me-action@a1f8d7237f0debbcc1fe514f362cd36582748827
        uses: ridedott/merge-me-action@v2.8.35
        with:
          # The GitHub login for which automatic merges are enabled. Supports micromatch.

          GITHUB_LOGIN: # optional, default is dependabot
          # A GitHub token.
          GITHUB_TOKEN: ${{ github.token }}
          # Represents available types of methods to use when merging a pull request. One of: MERGE, STASH or REBASE
          MERGE_METHOD: SQUASH # optional, default is SQUASH
          # Enable additional functionality to better personalize the behavior. One of: DEPENDABOT_MINOR or DEPENDABOT_PATCH.
          PRESET: # optional
          # Enable automatic merges when changes are made to the PR by a different author than the original one. Requires commits to be signed. One of: "true" or "false".
          ENABLED_FOR_MANUAL_CHANGES: false # optional, default is false
          # Maximum retry attempts to merge or get the PR information.
          MAXIMUM_RETRIES: 3 # optional, default is 3