version: "3.7"

volumes:
  heimdall:
  time-data:
networks:
  backend:

services:
  heimdall:
    image: "linuxserver/heimdall"
    container_name: "tp_heimdall"
    volumes:
      - heimdall:/config
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
    restart: unless-stopped
  timetagger:
    image: piaverous/timetagger:v21.3.3
    container_name: "tp_tagger"
    ports:
      - 8888:80
    networks:
      - backend
    volumes:
      - time-data:/root