[bgcolor c=#000]
    [color c=#fff]
        [container top=30% right=0% bottom=0% left=0%]
            [xcenter]
                [h size=12%]Welcome to Company![/h]
                [img url="https://img.shields.io/badge/-Microsoft_Azure-007ACC?style=flat-square&&logo=microsoft-azure&logoColor=white" width=54% height=17%][/img]
                [p][/p]
                [h size=6%]World leading in Cloud Technology Solutions[/h]
            [/xcenter]
        [/container]
    [/color]
[/bgcolor]