name: Auto-Merge

on:
  pull_request:
    branches:
      - main

jobs:
  pull-request:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Auto-Merge Pull Request
        # You may pin to the exact commit or the version.
        # uses: reitermarkus/automerge@72bc1353d0a084c84034be23424b124d900d1658
        uses: reitermarkus/automerge@v1.5.2
        with:
          # A GitHub Token other than the default `GITHUB_TOKEN` needs to be specified in order to be able to trigger other workflows.
          token: ${{ github.token }}
          # Specify which merge method to use. By default, will select the first one available in this order: `merge`, `squash`, `rebase`
          merge-method: squash
